name: dfc_flutter_firebase
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  avatar_glow: ^3.0.1
  cloud_firestore: ^5.6.2
  cloud_functions: ^5.3.1
  crypto: ^3.0.6
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_multi_formatter: ^2.13.0
  google_sign_in: ^6.2.2
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.4
  stream_transform: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.14
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/rei-codes/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
