name: dfc_flutter_firebase
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.1
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  crypto: ^3.0.1
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_multi_formatter: ^2.9.11
  google_sign_in: ^6.0.2
  image: ^4.0.15
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  provider: ^6.0.5
  sign_in_with_apple: ^4.1.0
  stream_transform: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics: ^5.4.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
