name: dfc_flutter_firebase
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  avatar_glow: ^2.0.1
  cloud_firestore: ^3.4.0
  cloud_functions: ^3.3.3
  crypto: ^3.0.1
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  extended_image: ^6.2.1
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.2
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_multi_formatter: ^2.3.3
  flutter_parsed_text: ^2.1.0
  google_sign_in: ^5.4.0
  image: ^3.0.1
  image_picker: ^0.8.3+1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  provider: ^6.0.0
  sign_in_with_apple: ^4.1.0
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics: ^4.15.2
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
