name: dfc_flutter_firebase
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: none

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  crypto: ^3.0.6
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_multi_formatter: ^2.13.0
  google_sign_in: ^6.2.1
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.3
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.13
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/paulkastel/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
