name: dfc_flutter_firebase
description: A new Flutter package project.
version: 1.0.1
homepage: distantfutu.re
publish_to: none

environment:
  sdk: ">=3.1.6 <4.0.0"

dependencies:
  avatar_glow: ^2.0.1
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.1.0
  crypto: ^3.0.1
  dfc_flutter:
    git: https://github.com/sgehrman/dfc_flutter
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_multi_formatter: ^2.9.11
  google_sign_in: ^6.0.2
  image: ^4.0.15
  image_picker: ^1.0.4
  intl: ^0.18.0
  json_annotation: ^4.8.0
  provider: ^6.0.5
  sign_in_with_apple: ^5.0.0
  stream_transform: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.6
  # must include this with dfc_lints. see https://github.com/dart-code-checker/dart-code-metrics/issues/254
  dart_code_metrics:
    git: https://github.com/paulkastel/dart-code-metrics
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
